apiVersion: apps/v1
kind: Deployment
metadata:
  name: elections-cluverse
  namespace: cluverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elections-cluverse
  template:
    metadata:
      labels:
        app: elections-cluverse
    spec:
      containers:
        - name: elections-cluverse
          image: akchikoussay/elections-cluverse:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cluverse-config
            - secretRef:
                name: cluverse-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: elections-cluverse
  namespace: cluverse
spec:
  selector:
    app: elections-cluverse
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
