apiVersion: v1
kind: Service
metadata:
  name: ingress-proxy-lb
  namespace: cluverse
spec:
  type: LoadBalancer
  selector:
    app: ingress-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
