apiVersion: v1
kind: Secret
metadata:
  name: cluverse-secrets
  namespace: cluverse
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: cluverse
  SPRING_DATASOURCE_PASSWORD: cluverse_pass
  MYSQL_ROOT_PASSWORD: cluverse_root
  MYSQL_DATABASE: cluverse
  MYSQL_USER: cluverse
  MYSQL_PASSWORD: cluverse_pass
  GROQ_API_KEY: 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
  STRIPE_SECRET_KEY: sk_test_51QyAl6LWllaI9swoL05VcpiEXVCSz8v0dX0wZaYukBPNYVgqwuOrux2R1n4uO8X3Z0YQJ9sQC4MZBsdg6i580MES009XTlptHr
  STRIPE_WEBHOOK_SECRET: whsec_c7c993f3e27b85dd050568860218cf953c176a92ea34ab5e50e48b86eda065a4
  OAUTH2_GOOGLE_CLIENT_ID: 601122724305-vnrngehk09s9ur8r8usm0s39upblk59v.apps.googleusercontent.com
  OAUTH2_GOOGLE_CLIENT_SECRET: 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
  OAUTH2_GITHUB_CLIENT_ID: Ov23li6njPWqPCqnDxZp
  OAUTH2_GITHUB_CLIENT_SECRET: 19ea13637efd331b40850d8d0148228e5e823e24

