apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-cluverse
  namespace: cluverse
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-cluverse
  template:
    metadata:
      labels:
        app: user-cluverse
    spec:
      containers:
        - name: user-cluverse
          image: akchikoussay/user-cluverse:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: cluverse-config
            - secretRef:
                name: cluverse-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 15
            failureThreshold: 5
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-cluverse
  namespace: cluverse
spec:
  selector:
    app: user-cluverse
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
